fonts:
    #kenvector_future:      {folder: , name: kenvector_future}
    kenvector_future:      {folder: , name: "Kenney Future"}
    kenvector_future_thin: {folder: , name: "Kenney Future Narrow"}
images:
    cursor:         { folder: gui/others, name: cursor }
    profile_image:  { folder: gui/others, name: cv }
    grey_panel:     { folder: gui/panels, name: grey }
    github_icon:    { folder: gui/others, name: github }
    linkedin_icon:  { folder: gui/others, name: linkedin }

    blue_button:    {folder: gui/Blue/Default, name: button_rectangle_depth_gloss}
    green_button:   {folder: gui/Green/Default, name: button_rectangle_depth_gloss}
    yellow_button:  {folder: gui/Yellow/Default, name: button_rectangle_depth_gloss}
    grey_button:    {folder: gui/Grey/Default, name: button_rectangle_depth_gloss}
    blue_circle:    {folder: gui/Blue/Default, name: check_round_color}
    yellow_circle:  {folder: gui/Yellow//Default, name: check_round_color}
    red_button:     {folder: gui/Red//Default, name: button_rectangle_depth_flat}
    grey8:          {folder: gui/Grey/Default, name: button_square_gloss}
    cross_white:    {folder: gui/Grey/Default, name: icon_outline_cross}
    cross_grey:     {folder: gui/Grey/Default, name: icon_outline_cross}
    
    minus_icon:     {folder: gui/others, name: minus}
    plus_icon:      {folder: gui/others, name: plus}
    info_icon:      {folder: gui/others, name: info}

sounds:
    bg:             {folder: "", name: music, extension: mp3}
    click:          {folder: "", name: click-a}
    back:           {folder: "", name: click-b}
    switch_up:      {folder: "", name: switch-b}
    switch_down:    {folder: "", name: switch-a}
    merge:          {folder: "", name: tap-a}