object_templates:
  settings_text:
    type: text
    font: kenvector_future
    font_size: 25
    color: [128,128,128]
  panel_text:
    type: text
    font: kenvector_future_thin
    font_size: 15
    color: Black
    text: ""
panels:
  game:
    objects:
      money_text:
        type: text
        font: freesansbold
        font_size: 35
        color: Green
        background_color: Black
        position: [ 1450, 995 ]
        text: ""
      level_text:
        extends: panel_text
        position: [ CENTER, 370 ]
      speed_text:
        extends: panel_text
        position: [ CENTER, 390 ]
      cooldown_text:
        extends: panel_text
        position: [ CENTER, 410 ]
      sell_price_text:
        extends: panel_text
        position: [ CENTER, 430 ]

  display_settings:
    objects:
      coming_soon_text:
        type: text
        font: kenvector_future
        font_size: 18
        color: [ 128,128,128 ]
        position: [ CENTER, 500 ]
        text: "THIS PAGE WILL COMING SOON..."

  audio_settings:
    objects:
      music_volume_text:
        extends: settings_text
        position: [CENTER, 380]
        text: "MUSIC VOLUME"
      sfx_volume_text:
        extends: settings_text
        position: [CENTER, 550]
        text: "SFX VOLUME"

  developer:
    objects:
      panel:
        position: [CENTER, CENTER]
        size: [300, 600]
        asset: grey_panel
      profile_image:
        position: [CENTER, 270]
        size: [100, 100]
        asset: profile_image
      name_text:
        type: text
        font: freesansbold
        color: Black
        font_size: 20
        position: [CENTER, 380]
        text: "Umutcan Ekinci"
      title_text:
        type: text
        font: freesansbold
        color: [128,128,128]
        font_size: 17
        position: [CENTER, 400]
        text: "Software Engineer"